name: Docker

on:
  push:
    branches: [main, docker_updates]
  release:
    types: [published]

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
  IMAGE_NAME: cdse-s2

jobs:
  push:
    name: Push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u $DOCKER_USER -p $DOCKER_TOKEN
      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME
      - name: Push image
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "main" ] && VERSION=latest
          echo VERSION=$VERSION
          echo DOCKER=$DOCKER_USER/$IMAGE_NAME:$VERSION
          docker tag $IMAGE_NAME $DOCKER_USER/$IMAGE_NAME:$VERSION
          docker push $DOCKER_USER/$IMAGE_NAME:$VERSION
