name: 🧪 Python Tests

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - '**'

  release:
    types: [ published ]

jobs:
  # Run python tests
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [ '3.9', '3.10', '3.12' ]
      fail-fast: true

    env:
      PYTHON_VERSION: ${{ matrix.python_version}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          pip install --no-cache-dir 'geopandas[all]'
          pip install pytest

      - name: Run unittests
        run: |
          echo "$(pwd)"
          export PYTHONPATH="${PYTHONPATH}:$(pwd)"
